export type BlogBlockType = 'paragraph' | 'h2' | 'h3' | 'list' | 'quote' | 'faq' | 'cta' | 'divider';
export type BlogBlock = { blockId: string; type: BlogBlockType; title?: string; text?: string };
export type ComplianceIssue = { id: string; severity: 'danger' | 'warning' | 'info'; category: string; phrase: string; reason: string; suggestion: string; blockId?: string };
export type BlogProject = {
  projectId: string;
  advertiserId: string;
  advertiserName: string;
  industry: string;
  platform: string;
  contentType: string;
  purpose: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  region: string;
  targetLength: number;
  tone: string;
  referenceText: string;
  titleOptions: string[];
  selectedTitle: string;
  blocks: BlogBlock[];
  status: 'draft' | 'writing' | 'review' | 'revision' | 'approved' | 'publish-ready' | 'published' | 'archived';
  complianceStatus: string;
  seoScore: number;
  complianceIssues: ComplianceIssue[];
  publishStatus: string;
  publishedUrl?: string;
  createdAt: string;
  updatedAt: string;
};
